camunda.bpm:
  admin-user:
    id: tnex
    password: Tnex@1234$$
  metrics:
    db-reporter-activate: false
  database:
    schema-update: create-drop
  filter:
    create: All tasks

spring:
  application:
    name: camunda-workflow
  datasource:
    url: jdbc:h2:mem:camunda-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      minimumIdle: 5
      maximumPoolSize: 50
      connectionTimeout: 2000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-update
        jdbc:
          lob:
            non_contextual_creation: false
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9090